# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: onebranch.pipeline.signing@1
  inputs:
    command: 'sign'
    signing_environment: 'azure-ado'
    search_root: '$(Build.SourcesDirectory)'
    files_to_sign: '**/*.py;*.py'


- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: '*.py commands'
    TargetFolder: '$(Build.SourcesDirectory)/out'